# Generated by Django 5.2.7 on 2025-11-04 18:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_timestamp_logentry_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicrequest',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AclEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('TOPIC', 'Topic'), ('GROUP', 'Group'), ('CLUSTER', 'Cluster')], max_length=20)),
                ('resource_name', models.CharField(blank=True, max_length=255)),
                ('principal', models.CharField(max_length=512)),
                ('permission', models.CharField(choices=[('READ', 'Read'), ('WRITE', 'Write'), ('DESCRIBE', 'Describe'), ('CREATE', 'Create'), ('DELETE', 'Delete'), ('ALL', 'All'), ('READ_WRITE', 'Read/Write')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_acls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
