# Generated by Django 5.2.7 on 2025-12-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_topicrequest_reviewed_at_aclentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicrequest',
            name='request_type',
            field=models.CharField(choices=[('CREATE', 'Create Topic'), ('DELETE', 'Delete Topic')], default='CREATE', max_length=20),
        ),
    ]
